name: Deploy to Production Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run test

  build_and_deploy:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRACK_IT_3C706 }}'
          channelId: live
          projectId: track-it-3c706
